In [1]:
import kneed
import sklearn
from kneed import KneeLocator
from sklearn.cluster import KMeans
from collections import Counter
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

In [2]:
def K(data):

    inertias = []
    for i in range(1,11):
        kmeans = KMeans(n_clusters=i)
        kmeans.fit(data)
        inertias.append(kmeans.inertia_)

    kl = KneeLocator(range(1, 11), inertias, curve="convex", direction="decreasing")
    return kl.elbow


In [3]:
def labelClusters(klabels, labels):
    """"
    labelClusters Input: data, and labels associated with data

as kmeans randomly assigns labels to its clusters, it is the job of labelCLusters to find which real 
label is associated with the randomly generated ones. It does this by first creating a dictionary (tDict) that 
observes how many times each real label occurs with a randomly generated one. Another dictionary (sDict) is used 
to find which label is most associated with which random value.

returns: sDict gets returned.

    """
   
    print(klabels)
    print(labels)
   
    tDict = {}
    sDict = {}
    gSList = set(labels)
    glist = []
    
    if len(set(klabels)) != len(gSList):
        return "ERROR: number of clusters does not match with number of labels!"
    
#make dictionary of unique labels associated with clusters to later measure which is more associated with what clusters
    for x in gSList:
        glist.append(x)
        for l in range(len(gSList)):
            tDict[str(x) + str(l)] = 0 #initialize total dictionary
            sDict[x] = 0
            
#put the actual values into dictionary that counts the number of cluster instances for each    
    
    for b in range(len(labels)): 
        for t in tDict:
            if t[:len(t)-1] == str(labels[b]) and t[len(t)-1:] == str(klabels[b]):
                tDict[t] = tDict.get(t) + 1
    print(tDict)

    while len(glist) > 1:
        for x in range(len(gSList)-1):
            a = glist[0]
            for y in range(1, len(glist)):
                if tDict[str(a) + str(x)] < tDict[str(glist[y]) + str(x)]:
                    a = glist[y]
                sDict[a] = x
            glist.remove(a)
    sDict[glist[0]] = len(gSList)-1
    
                
    return sDict

In [4]:
X, y = make_blobs(n_samples=20, centers=3, n_features=2,
...                   random_state=0)
>>> print(X)
z = []
Count = 0
for x in y:
   
    if y[x] == 1:
        z.append("dog")
    if y[x] == 0:
        z.append("cat")
    if y[x] == 2:
        z.append("horse")
       
    #z.append(str(y[x]))
    Count=Count+1
print(z)


[[ 1.12031365  5.75806083]
 [-1.91423083  2.61557951]
 [ 1.28933778  3.44969159]
 [ 2.21021495  1.27582618]
 [ 4.32502215 -0.55670201]
 [-2.57545698  1.49786432]
 [-3.2331742   4.86865766]
 [ 1.16748177 -1.08313281]
 [ 0.87305123  4.71438583]
 [ 1.9263585   4.15243012]
 [ 3.58804674  2.36702243]
 [ 2.47034915  4.09862906]
 [-0.49772229  1.55128226]
 [ 2.10102604  0.71047981]
 [ 1.7373078   4.42546234]
 [-2.03655619  2.47980796]
 [-0.29661333  4.12026211]
 [-1.87481616  3.07423123]
 [ 2.91970372  0.15549864]
 [ 1.42013331  4.63746165]]
['cat', 'cat', 'cat', 'horse', 'horse', 'cat', 'cat', 'horse', 'cat', 'cat', 'horse', 'cat', 'horse', 'horse', 'cat', 'cat', 'cat', 'cat', 'horse', 'cat']


In [5]:
k =K(X)
kmeans = KMeans(n_clusters=k)
kmeans.fit(X)

KMeans(n_clusters=3)

In [6]:
labelClusters(kmeans.labels_, y)

[1 2 1 0 0 2 2 0 1 1 0 1 2 0 1 2 1 2 0 1]
[0 2 0 1 1 2 2 1 0 0 1 0 1 1 0 2 2 2 1 0]
{'00': 0, '01': 7, '02': 0, '10': 6, '11': 0, '12': 1, '20': 0, '21': 1, '22': 5}


{0: 1, 1: 0, 2: 2}

In [7]:
print(kmeans.labels_)
print(y)
print(Count)

[1 2 1 0 0 2 2 0 1 1 0 1 2 0 1 2 1 2 0 1]
[0 2 0 1 1 2 2 1 0 0 1 0 1 1 0 2 2 2 1 0]
20
