In [1]:
from sklearn.cluster import KMeans
import clusters as cl
from sklearn.datasets import make_blobs
import minisom
from minisom import MiniSom 
import pandas as pd
import csv
import numpy as np

# this will reload modules that have changed
%load_ext autoreload
%autoreload 2

In [7]:
columns=['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']
data = pd.read_csv('iris_features.csv', 
                    header=0, sep='\t+', engine='python')
labelz = pd.read_csv('iris_labels.csv', header = 0)
labels = labelz.values.tolist()

#target = data['target'].values
#label_names = {1:'Kama', 2:'Rosa', 3:'Canadian'}
#data = data[data.columns[:-1]]
# data normalization
#data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
#data = data.values
#print(data)
#print(labelz)
#print(labels)
dlist = []
for x in range(len(data)):
    dlist.append(list(data.loc[x]))
darr = np.array(dlist)
print(darr)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
#file = open("iris_features.csv", "r")
#data = list(csv.reader(file, delimiter=""))
#file.close()
#print(data)

In [9]:
#X, y = make_blobs(n_samples=20, centers=3, n_features=2,
#...                   random_state=0)
#>>> print(X)


In [10]:
k = cl.K(darr)
kmeans = KMeans(n_clusters=k)
kmeans.fit(darr)

KMeans(n_clusters=3)

In [11]:
print(kmeans.labels_)
print(labelz)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]
         label
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]


In [12]:
cl.labelClusters(kmeans.labels_, labels)

TypeError: unhashable type: 'list'

In [ ]:
def use_kmeans(darr, tlabels):
    k = cl.K(data)
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(data)
    
    #cl.plotKMeans(data, tlabels)
    
    return kmeans, cl.randIndex(kmeans.labels_, tlabels), k
    

In [ ]:
use_kmeans(darr, labelz)

In [ ]:
som = MiniSom(6, 6, 2, sigma=0.3, learning_rate=0.5) # initialization of 6x6 SOM
som.train(X, 100) # trains the SOM with 100 iterations

In [ ]:
som.winner(data[0])

In [ ]:
somlist = []

In [ ]:
#MAKE BMU LIST
for x in range(len(data)):
    somlist.append(som.winner(data[x]))
print(somlist)

In [ ]:
use_kmeans(somlist, y)

In [ ]:
use_kmeans(somlist, kmeans.labels_)